# @package agent
_target_: agent.tdmpc.Agent
obs_type: ${obs_type}
frame_cnt: ${frame_count}
img_sz: 64
latent_dim: 5
action_dim: ???
obs_shape: ???
lr: 1e-3
nums_samples: 500
num_pi_trajs: 20
num_horizon: 5
iterations: 6
rho: 0.5
consistency_coef: 2
reward_coef: 0.5
value_coef: 0.1
device: ${device}




