defaults:
  - _self_
  - agent: bcrl
  - suite: atari
  - override hydra/launcher: submitit_local

# replay buffer
replay_buffer_size: 150000
replay_buffer_num_workers: 2
nstep: 10
batch_size: 32
episode_length: ???
per_beta: 0.4 # from tdmpc
per_alpha: 0.6 # from tdmpc
# misc
seed: 0
device: cpu
save_video: true
save_train_video: false
use_tb: true
target_update_freq: 2
tau: 0.01

# experiment
obs_type: 'features'
reward_type: 'dense' # dense, sparse
experiment: rl
frame_count: 3
exp_id: 'change_this'

# snapshot
save_snapshot: true
snapshot_interval: 300 # seconds (5mins)
num_snapshots: 5
# checkpoints
save_checkpoint: true
checkpoint_every: 100000 # steps
load_checkpoint_path: null

# expert dataset
num_demos: 100
expert_dataset: /Users/subhojeetbose/Downloads/assignment 3/bc.pkl

hydra:
  run:
    dir: ./exp_local/${exp_id}

